x <- read.csv(commandArgs(trailingOnly=TRUE)[1], sep = ",", header = F)
S1 <- mean(x$V1)
S1SD <- sd(x$V1)
S2 <- mean(x$V2)
S2SD <- sd(x$V2)
S3 <- mean(x$V3)
S3SD <- sd(x$V3)
Ph <- mean(x$V4)
PhSD <- sd(x$V4)
cat(S1, S1SD, S2, S2SD, S3, S3SD, Ph, PhSD, "\n", file="average.csv", append=T, sep = ",")
